#!/bin/sh

# Only exported variables can be used within the timer's command.
export brightness="$(light)"
# Run xidlehook
xidlehook \
  `# Don't lock when there's a fullscreen application` \
  --not-when-fullscreen \
  `# Don't lock when there's audio playing` \
  --not-when-audio \
  `# Dim the screen after t seconds, undim if user becomes active` \
  --timer $1 \
    'light -S .1' \
    '' \
  `# Undim & lock after 5 more seconds` \
  --timer 5 \
    'light -S $brightness; i3lock-fancy' \
    '' \
  `# Finally, suspend an hour after it locks` \
  --timer 900 \
    'systemctl suspend' \
    ''
